// <auto-generated />
using HRManager.APIv2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManager.APIv2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CandidateWorkingPlace", b =>
                {
                    b.Property<string>("CandidatesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkingPlacesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CandidatesId", "WorkingPlacesId");

                    b.HasIndex("WorkingPlacesId");

                    b.ToTable("CandidateWorkingPlace");
                });

            modelBuilder.Entity("HRManager.APIv2.Models.Candidate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CandidateFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfApplication")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EducationDegree")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Employment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("HRManager.APIv2.Models.EducationDegree", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EducationDegrees");

                    b.HasData(
                        new
                        {
                            Id = "91dd93b1-403c-4913-b7fe-917bb0c35996",
                            Name = "univ. bacc. ing."
                        },
                        new
                        {
                            Id = "151dba72-2400-43d6-9e33-cadbb71b865b",
                            Name = "mag. ing."
                        },
                        new
                        {
                            Id = "510df9ac-baca-43b6-9e4a-cdda5f419428",
                            Name = "dr. sc."
                        });
                });

            modelBuilder.Entity("HRManager.APIv2.Models.Interview", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DateOfEmployment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DateOfInterview")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Evaluation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SelectEmployment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("HRManager.APIv2.Models.Position", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = "151dba72-2400-43d6-9e33-cadbb71b865b",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = "510df9ac-baca-43b6-9e4a-cdda5f419428",
                            Name = "Frontend"
                        });
                });

            modelBuilder.Entity("HRManager.APIv2.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = "151dba72-2400-43d6-9e33-cadbb71b865b",
                            Email = "marko@gmail.com",
                            FirstName = "Marko",
                            LastName = "Curlin",
                            Role = "Admin",
                            UserName = "marko@gmail.com"
                        },
                        new
                        {
                            Id = "510df9ac-baca-43b6-9e4a-cdda5f419428",
                            Email = "ana@gmail.com",
                            FirstName = "Ana",
                            LastName = "Anic",
                            Role = "Edit",
                            UserName = "ana@gmail.com"
                        },
                        new
                        {
                            Id = "91dd93b1-403c-4913-b7fe-917bb0c35996",
                            Email = "filip@gmail.com",
                            FirstName = "Filip",
                            LastName = "Filic",
                            Role = "View",
                            UserName = "filip@gmail.com"
                        });
                });

            modelBuilder.Entity("HRManager.APIv2.Models.WorkingPlace", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("WorkingPlaces");

                    b.HasData(
                        new
                        {
                            Id = "151dba72-2400-43d6-9e33-cadbb71b865b",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = "510df9ac-baca-43b6-9e4a-cdda5f419428",
                            Name = "Frontend"
                        });
                });

            modelBuilder.Entity("CandidateWorkingPlace", b =>
                {
                    b.HasOne("HRManager.APIv2.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManager.APIv2.Models.WorkingPlace", null)
                        .WithMany()
                        .HasForeignKey("WorkingPlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRManager.APIv2.Models.Interview", b =>
                {
                    b.HasOne("HRManager.APIv2.Models.Candidate", null)
                        .WithMany("Interviews")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRManager.APIv2.Models.Candidate", b =>
                {
                    b.Navigation("Interviews");
                });
#pragma warning restore 612, 618
        }
    }
}
